`uvm_analysis_imp_decl(_lite)
`uvm_analysis_imp_decl(_mem)
`uvm_analysis_imp_decl(_stream)

// Actual value is given by monitor, expected value is generated by scoreboard
class dma_scoreboard extends uvm_scoreboard;
  `uvm_component_utils(dma_scoreboard)
  // Address Map Constants
  localparam bit [31:0] CONTROL_REG     = 32'h4000_0000;
  localparam bit [31:0] STATUS_REG      = 32'h4000_0004;
  localparam bit [31:0] SOURCE_ADDR_REG = 32'h4000_0018;
  localparam bit [31:0] LENGTH_REG      = 32'h4000_0028;
  // Queues & Trackers
 // Queues & Trackers
bit [31:0] actual_rdata_q[$],actual_tdata_q[$];
logic [31:0] control_r;
logic [31:0] status_r;
logic [31:0] length_r;
logic [31:0] source_addr_r;
logic [31:0] remaining_bytes;
logic [31:0] address_progression;
logic [31:0] actual_start_addr;
// Burst Information
logic [7:0] actual_arlen;
logic [7:0] expected_arlen;
logic [7:0] num_of_beat_per_trnsf = 0;
logic [2:0] actual_arsize;
// Last transfer tracking
logic [2:0] last_bytes;
// Stream information
logic [31:0] actual_rdata;
logic [31:0] actual_tdata;
logic [31:0] expected_data,actual_data;
logic [3:0] actual_tkeep;
logic actual_tlast;
logic expected_tlast;
  // UVM Implementation Ports
  uvm_analysis_imp_lite   #(axi_lite_sequence_item,   dma_scoreboard) imp_lite;
  uvm_analysis_imp_mem    #(axi_sequence_item,        dma_scoreboard) imp_mem;
  uvm_analysis_imp_stream #(axi_stream_sequence_item, dma_scoreboard) imp_stream;

  function new(string name = "dma_scoreboard", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    imp_lite   = new("imp_lite",   this);
    imp_mem    = new("imp_mem",    this);
    imp_stream = new("imp_stream", this);
  endfunction

  // --- 1. AXI-Lite Writes (Programming Registers) ---
  virtual function void write_lite(axi_lite_sequence_item lite_item);
    if (lite_item.write_req) begin
       $display("ENTERED write_lite");
       $display("addr=%h data=%h", lite_item.addr, lite_item.data);

      case (lite_item.addr)
        CONTROL_REG:   begin
          control_r = lite_item.data;
        $display("Matched CONTROL");
        end
        STATUS_REG:   begin
          status_r  = lite_item.data;
         $display("Matched STATUS");
        end
        SOURCE_ADDR_REG: begin
          source_addr_r       = lite_item.data;
           $display("Matched SOURCE");
          address_progression = source_addr_r;
        end
        LENGTH_REG: begin
          $display("Matched LENGTH");
          length_r        = lite_item.data;
          remaining_bytes = length_r;
          $display("Length = %0d", length_r);
        end
      endcase
    end
  endfunction
  // --- 2. Memory Read Transactions ---
virtual function void write_mem(axi_sequence_item mem_item);
$display("[%0t] ENTERED write_mem", $time);
$display("--------------------------------");
$display("Entered write_axi");
$display("time=%0t", $time);
$display("start_addr=%h", mem_item.start_addr);
    //actual_rdata      = mem_item.data;
    actual_start_addr = mem_item.start_addr;
    actual_arlen      = mem_item.len;
    actual_arsize     = mem_item.size;
    // First beat of every burst
    if(num_of_beat_per_trnsf == 0) begin
        check_burst_start_address();
        check_burst_generation();
        num_of_beat_per_trnsf = mem_item.len + 1;
    end
    $display("Expected queue before = %0d", actual_rdata_q.size());
    foreach(mem_item.data[i])begin
    actual_rdata_q.push_back(mem_item.data[i]);
    num_of_beat_per_trnsf--;
    end
    $display("Expected queue after = %0d", actual_rdata_q.size());
endfunction

  // --- 3. Stream Output Transactions ---
  virtual function void write_stream
(
    axi_stream_sequence_item stream_item
);
$display("[%0t] ENTERED write_stream", $time);
    actual_tdata = stream_item.tdata;
    actual_tlast = stream_item.tlast;
    actual_tkeep = stream_item.tkeep;
    $display("remaining=%0d  TLAST=%0b", remaining_bytes, actual_tlast);
    $display("remaining before compare = %0d", remaining_bytes);
    actual_tdata_q.push_back(stream_item.tdata);
    while(actual_rdata_q.size()&& actual_tdata_q.size())begin
       compare();
    end
    check_tlast_correctness();
    if(expected_tlast) begin
        check_tkeep_correctness();
        if(remaining_bytes != 0)
            `uvm_fatal("DMA_SB",
                       "TLAST asserted before transfer completed.");
    end
endfunction
  virtual task run_phase(uvm_phase phase);
    super.run_phase(phase);
  endtask
  // --- Checker Methods ---
  function void compare();
    if(actual_rdata_q.size() == 0)
        `uvm_fatal("DMA_SB",
                   "Received AXI Stream data while expected queue is empty.")
    expected_data = actual_rdata_q.pop_front();
    actual_data=actual_tdata_q.pop_front();
    if(actual_data != expected_data) begin
    $display("printing the two values %d,%d",actual_tdata,expected_data);
        `uvm_fatal("DMA_SB",
            $sformatf("TDATA Mismatch! Expected : 0x%08h Got : 0x%08h",
                       expected_data,
                       actual_data))
    end
    if(remaining_bytes > 4) begin
        remaining_bytes -= 4;
    end
    else begin
        last_bytes      = remaining_bytes;
        remaining_bytes = 0;
    end
    $display("Queue size=%0d", actual_rdata_q.size());
endfunction
  function void check_tkeep_correctness();
    case(last_bytes)
        3'd1:
            if(actual_tkeep != 4'b0001)
                `uvm_fatal("DMA_SB","Incorrect TKEEP for 1 byte.")
        3'd2:
            if(actual_tkeep != 4'b0011)
                `uvm_fatal("DMA_SB","Incorrect TKEEP for 2 bytes.")
        3'd3:
            if(actual_tkeep != 4'b0111)
                `uvm_fatal("DMA_SB","Incorrect TKEEP for 3 bytes.")
        3'd4:
            if(actual_tkeep != 4'b1111)
                `uvm_fatal("DMA_SB","Incorrect TKEEP for 4 bytes.")
        default: ;
    endcase
    $display("SCB, the tkeep was correct and the transfer is complete.");
endfunction
//-------------------------------------------------
  function void check_tlast_correctness();
    expected_tlast = (remaining_bytes == 0);
    if(actual_tlast != expected_tlast)begin
        `uvm_fatal("DMA_SB",
        $sformatf("TLAST mismatch! Expected : %0b Got : %0b",
                   expected_tlast,
                   actual_tlast));
    end
    //else      $display("SCB, the tlast was correct and the transfer is complete.");
endfunction
//----------------------------------------------------
  function void check_burst_generation();
    logic [31:0] next_boundary;
    logic [31:0] distance_to_boundary;
    logic [31:0] expected_bytes;
    logic [31:0] max_dma_burst_bytes = 1024;
    //---------------------------------------
    // Compute next 4KB boundary
    //---------------------------------------
    next_boundary =
    (address_progression & 32'hFFFF_F000) + 32'h1000;
    distance_to_boundary =
    next_boundary - address_progression;
    //---------------------------------------
    // Smallest allowable burst
    //---------------------------------------
    expected_bytes = remaining_bytes;
    if(distance_to_boundary < expected_bytes)
        expected_bytes = distance_to_boundary;
    if(max_dma_burst_bytes < expected_bytes)
        expected_bytes = max_dma_burst_bytes;
    //---------------------------------------
    // Expected ARLEN
    //---------------------------------------
    if(expected_bytes == 0)
        expected_arlen = 0;
    else
        expected_arlen = ((expected_bytes + 3)/4)-1;
    //---------------------------------------
    // Compare ARLEN
    //---------------------------------------
    if(expected_arlen != actual_arlen)
        `uvm_fatal("DMA_SB",
        $sformatf(
        "ARLEN Mismatch! Expected : %0d Got : %0d",
        expected_arlen,
        actual_arlen))
    //---------------------------------------
    // Compare ARSIZE
    //---------------------------------------
    if(actual_arsize != 3'b010)
        `uvm_fatal("DMA_SB",
        $sformatf(
        "ARSIZE Mismatch! Expected : 3'b010 Got : %03b",
        actual_arsize))
    //---------------------------------------
    // Prepare next burst start address
    //---------------------------------------
    $display("Updating address_progression");
$display("Old = %h", address_progression);

    address_progression += expected_bytes;
    $display("New = %h", address_progression);
endfunction

  function void check_burst_start_address();
    if(actual_start_addr != address_progression) begin
        `uvm_fatal("DMA_SB",
        $sformatf(
        "Burst Start Address Mismatch! Expected : 0x%08h Got : 0x%08h",
        address_progression,
        actual_start_addr))
    end
endfunction
endclass
